% Load results
clear all
close all
load('data/pairwiseSegregated.mat')
% Create meshgrids for r and z
[R,Z] = meshgrid(r,z);
%% Temperature plot
figure(1);
color = hot; % Cool (hot) colors
surf(R,Z,T) % plot
xlim([min(min(r)) max(max(r))]);
ylim([min(min(z)) max(max(z))]);
zlim([min(min(T)), max(max(T))]);
xlabel('$r\quad\left[\SI{}{\meter}\right]$');
ylabel('$z\quad\left[\SI{}{\meter}\right]$');
zlabel('$T\quad\left[\SI{}{\kelvin}\right]$');
title('Temperature in the reactor');
colormap(color(1:end-10,:));
[az,el] = view;
view(az+90,el);
set(gcf,'position',[0 0 1366/2 768/2])
cleanfigure;
matlab2tikz('fig/temperature.tikz',...
            'parseStrings',false,...
            'standalone',true,...
            'extraAxisOptions',{'scaled x ticks = false', ...
            ['x tick label style={/pgf/number format/fixed,'...
             '/pgf/number format/precision=2,'...
             '/pgf/number format/zerofill=true}'],...
             'z buffer = sort'},...
            'extraCode',{'\usepackage{siunitx}'});
system(['cd fig && '...
        'pdflatex temperature.tikz && '...
        'rm temperature.aux temperature.log']);
%% Velocity
figure(2);
color = jet; % Cool colors
surf(R,Z,uz) % plot
xlim([min(min(r)) max(max(r))]);
ylim([min(min(z)) max(max(z))]);
zlim([min(min(uz)), max(max(uz))]);
xlabel('$r\quad\left[\SI{}{\meter}\right]$');
ylabel('$z\quad\left[\SI{}{\meter}\right]$');
zlabel('$u_z\quad\left[\SI{}{\meter\per\second}\right]$');
title('Velocity in the reactor');
colormap(color(1:end-10,:));
[az,el] = view;
view(az+90,el);
set(gcf,'position',[0 0 1366/2 768/2])
cleanfigure;
matlab2tikz('fig/velocity.tikz',...
            'parseStrings',false,...
            'standalone',true,...
            'extraAxisOptions',{'scaled x ticks = false', ...
            ['x tick label style={/pgf/number format/fixed,'...
             '/pgf/number format/precision=2,'...
             '/pgf/number format/zerofill=true}'],...
             'z buffer = sort'},...
            'extraCode',{'\usepackage{siunitx}'});
system(['cd fig && '...
        'pdflatex velocity.tikz && '...
        'rm velocity.aux velocity.log']);
%% Density
figure(3);
surf(R,Z,rho) % plot
xlim([min(min(r)) max(max(r))]);
ylim([min(min(z)) max(max(z))]);
zlim([min(min(rho)), max(max(rho))]);
xlabel('$r\quad\left[\SI{}{\meter}\right]$');
ylabel('$z\quad\left[\SI{}{\meter}\right]$');
zlabel('$\rho\quad\left[\SI{}{\kilogram\per\cubic\meter}\right]$');
title('Density in the reactor');
colormap(color(1:end-10,:));
[az,el] = view;
view(az+90,el);
set(gcf,'position',[0 0 1366/2 768/2])
cleanfigure;
matlab2tikz('fig/density.tikz',...
            'parseStrings',false,...
            'standalone',true,...
            'extraAxisOptions',{'scaled x ticks = false', ...
            ['x tick label style={/pgf/number format/fixed,'...
             '/pgf/number format/precision=2,'...
             '/pgf/number format/zerofill=true}'],...
             'z buffer = sort'},...
            'extraCode',{'\usepackage{siunitx}'});
system(['cd fig && '...
        'pdflatex density.tikz && '...
        'rm density.aux density.log']);